### ISSUE TITLE
[BUG] Error thrown on every folder expansion/collapse

### ISSUE THREAD

**Issue by esheyw** [ironmonk88/multiple-document-selection#13]
**Describe the bug**
with MDS active, any time I expand or collapse a folder in any directory, I get the following error:
```
multiple-document-selection.js:657 Uncaught TypeError: Cannot read properties of undefined (reading '0')
[Detected 1 package: multiple-document-selection]
    at HTMLOListElement.<anonymous> (multiple-document-selection.js:657:39)
    at HTMLOListElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```
happens even as the only active module, in both pf2e and dnd5e/foundry current.

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
